export type Page =
  | 'home'
  | 'cours'
  | 'vocabulaire'
  | 'grammaire'
  | 'conversations'
  | 'listening'
  | 'prononciation'
  | 'quiz'
  | 'test-niveau'
  | 'anglais-professionnel'
  | 'progression'
  | 'lesson'
  | 'not-found'
